#!/bin/bash

echo "Lets do this."
echo -e "------------------\n"
sudo -v

echo -e "Firstly, make sure google drive is running if you want to set up mackup."

echo -e "Do you want to set a hostname for this machine? (y/n)"
read -p "Answer: " reply

if [[ $reply =~ ^[Yy]$ ]]
then
    echo "What do you want your computer hostname to be?"
    read -p "Answer: " reply
    hostnamectl set-hostname $reply
fi


echo -e "Set up terminal\n"
source $HOME/dotfiles/setup-terminal

echo -e "Set up development environment\n"
source $HOME/dotfiles/setup-dev

echo -e "Set up sensible mac defaults\n"
source $HOME/dotfiles/mac/set-defaults.sh

echo -e "All done\n"
